name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: nix build
        run: |
          nix build
          cp result resume.pdf
      - uses: actions/upload-artifact@v5
        with:
          name: resume
          path: resume.pdf
          if-no-files-found: error

  submit-update-pr:
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v6
        with:
          repository: sumnerevans/sumnerevans.com

      - name: Update the resume
        uses: actions/download-artifact@v6
        with:
          name: resume
          path: content/portfolio

      - run: git status

      - name: Create PR against website repository
        id: cpr
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.PR_CREATOR_TOKEN }}
          commit-message: "resume: update to ${{ github.sha }}"
          title: "resume: update to ${{ github.sha }}"
          branch: update-resume
          delete-branch: true

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
